// Code generated by MockGen. DO NOT EDIT.
// Source: ../service.go
//
// Generated by this command:
//
//	mockgen -source=../service.go -destination=repo_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUsersRepo is a mock of UsersRepo interface.
type MockUsersRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUsersRepoMockRecorder
	isgomock struct{}
}

// MockUsersRepoMockRecorder is the mock recorder for MockUsersRepo.
type MockUsersRepoMockRecorder struct {
	mock *MockUsersRepo
}

// NewMockUsersRepo creates a new mock instance.
func NewMockUsersRepo(ctrl *gomock.Controller) *MockUsersRepo {
	mock := &MockUsersRepo{ctrl: ctrl}
	mock.recorder = &MockUsersRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersRepo) EXPECT() *MockUsersRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUsersRepo) Create(ctx context.Context, email, passwordHash string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, email, passwordHash)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUsersRepoMockRecorder) Create(ctx, email, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUsersRepo)(nil).Create), ctx, email, passwordHash)
}

// GetByEmail mocks base method.
func (m *MockUsersRepo) GetByEmail(ctx context.Context, email string) (uuid.UUID, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUsersRepoMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUsersRepo)(nil).GetByEmail), ctx, email)
}

// MockSessionsRepo is a mock of SessionsRepo interface.
type MockSessionsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSessionsRepoMockRecorder
	isgomock struct{}
}

// MockSessionsRepoMockRecorder is the mock recorder for MockSessionsRepo.
type MockSessionsRepoMockRecorder struct {
	mock *MockSessionsRepo
}

// NewMockSessionsRepo creates a new mock instance.
func NewMockSessionsRepo(ctrl *gomock.Controller) *MockSessionsRepo {
	mock := &MockSessionsRepo{ctrl: ctrl}
	mock.recorder = &MockSessionsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionsRepo) EXPECT() *MockSessionsRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSessionsRepo) Create(ctx context.Context, userID uuid.UUID, refreshHash []byte, expiresAt time.Time) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, refreshHash, expiresAt)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSessionsRepoMockRecorder) Create(ctx, userID, refreshHash, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionsRepo)(nil).Create), ctx, userID, refreshHash, expiresAt)
}

// GetByRefreshHash mocks base method.
func (m *MockSessionsRepo) GetByRefreshHash(ctx context.Context, refreshHash []byte) (uuid.UUID, uuid.UUID, time.Time, *time.Time, *uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRefreshHash", ctx, refreshHash)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(uuid.UUID)
	ret2, _ := ret[2].(time.Time)
	ret3, _ := ret[3].(*time.Time)
	ret4, _ := ret[4].(*uuid.UUID)
	ret5, _ := ret[5].(error)
	return ret0, ret1, ret2, ret3, ret4, ret5
}

// GetByRefreshHash indicates an expected call of GetByRefreshHash.
func (mr *MockSessionsRepoMockRecorder) GetByRefreshHash(ctx, refreshHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRefreshHash", reflect.TypeOf((*MockSessionsRepo)(nil).GetByRefreshHash), ctx, refreshHash)
}

// RevokeAllForUser mocks base method.
func (m *MockSessionsRepo) RevokeAllForUser(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllForUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllForUser indicates an expected call of RevokeAllForUser.
func (mr *MockSessionsRepoMockRecorder) RevokeAllForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllForUser", reflect.TypeOf((*MockSessionsRepo)(nil).RevokeAllForUser), ctx, userID)
}

// RevokeAndReplace mocks base method.
func (m *MockSessionsRepo) RevokeAndReplace(ctx context.Context, oldID, newID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAndReplace", ctx, oldID, newID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAndReplace indicates an expected call of RevokeAndReplace.
func (mr *MockSessionsRepoMockRecorder) RevokeAndReplace(ctx, oldID, newID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAndReplace", reflect.TypeOf((*MockSessionsRepo)(nil).RevokeAndReplace), ctx, oldID, newID)
}
